name: JE Vasshaug
favicon: null
layout_spectrum: 0.37129
typography_spectrum: 0.63563
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#524741'
    - '#346051'
    - '#86765c'
    - '#5b866b'
    - '#b98c48'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
